name: FeatureManagement-Dotnet CI

on:
  push:
    branches:
      - main
      - preview
      - release/*
  pull_request:
    branches:
      - main
      - preview
      - release/*

permissions:
  security-events: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install .NET
        run: pwsh build/install-dotnet.ps1 -RestoreOnly

      - name: Restore
        run: pwsh build.ps1 -RestoreOnly

      - name: Initialize CodeQL
        uses: github/codeql-action/init@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        with:
          languages: 'csharp'

      - name: Dotnet Build
        run: pwsh build.ps1

      - name: Dotnet Pack
        run: pwsh pack.ps1

      - name: Dotnet Test
        run: pwsh test.ps1

      - name: Publish Test Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Unit Test Results
          path: ${{ github.workspace }}/tests/**/*.trx

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
