name: FeatureManagement-Dotnet CI

on:
  push:
    branches:
      - main
      - preview
      - release/*
  pull_request:
    branches:
      - main
      - preview
      - release/*

permissions:
  security-events: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Install .NET
        run: pwsh build/install-dotnet.ps1 -RestoreOnly

      - name: Restore
        run: pwsh build.ps1 -RestoreOnly

      - name: Initialize CodeQL
        uses: github/codeql-action/init@f3712979fa5f215279b101dd0a2e3bdfb4353324 # v3.37.7
        with:
          languages: 'csharp'

      - name: Dotnet Build
        run: pwsh build.ps1

      - name: Dotnet Pack
        run: pwsh pack.ps1

      - name: Dotnet Test
        run: pwsh test.ps1

      - name: Publish Test Results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Unit Test Results
          path: ${{ github.workspace }}/tests/**/*.trx

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@f3712979fa5f215279b101dd0a2e3bdfb4353324 # v3.37.7
